services:
  - type: web
    name: portfolio-backend
    env: python
    region: oregon
    plan: free

    # install your dependencies from the monorepo root
    buildCommand: pip install -r backend/requirements.txt

    # Render will run this from your repo root
    startCommand: python backend/start.py

    envVars:
      # standard Flask env
      - key: FLASK_ENV
        value: production

      # point SQLAlchemy at the disk-mounted SQLite DB
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/data/portfolio.db

      # mail credentials – keep these off-sync so you enter them manually in the dashboard
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false

      # you can hardcode this
      - key: RECIPIENT_EMAIL
        value: donghyeunlee1@gmail.com

      # auto‑generate a strong SECRET_KEY for you
      - key: SECRET_KEY
        generateValue: true

      # your GitHub Pages origin – hardcode so it’s immediately available
      - key: CORS_ORIGINS
        value: https://kiryuchi10.github.io

    # attach 1 GB of persistent storage for your .db file
    disk:
      name: portfolio-data
      mountPath: /opt/render/project/data
      sizeGB: 1
